config/routes.rb
Rails.application.routes.draw do
  get 'pages/show'

  devise_for :users
  root 'users#index'
  resources :users, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monster.rb
class Monster < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # devise機能全部盛り
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_or_unset_current_user_id_on_cookies
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def set_or_unset_current_user_id_on_cookies
    cookies.encrypted[:user_id] = (current_user.id if current_user)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /users or /users.json
  def index
    @online_users = User.where.not(online_at: nil).order(online_at: :desc)
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  # def show
  # end

  # GET /users/new
  # def new
  #   @user = User.new
  # end

  # GET /users/1/edit
  # def edit
  # end

  # POST /users or /users.json
  # def create
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: "User was successfully created." }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /users/1 or /users/1.json
  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: "User was successfully updated." }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /users/1 or /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: "User was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | sandbox
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      nav
        - if user_signed_in?
          strong
            = current_user.name
          br
          strong
            = link_to current_user.email, pages_show_path
          br
          = link_to 'プロフィール変更', edit_user_registration_path
          br
          = link_to 'ログアウト', destroy_user_session_path, method: :delete
        - else
          = link_to 'サインアップ', new_user_registration_path
          br
          = link_to 'ログイン', new_user_session_path
    p.notice
      = notice
    p.alert
      = alert
    = yield

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/users/_form.html.slim
= form_for(user) do |f|
  - if user.errors.any?
    #error_explanation
      h2
        = pluralize(user.errors.count, "error")
        |  prohibited this user from being saved:
      ul
        - user.errors.full_messages.each do |message|
          li
            = message
  .actions
    = f.submit

app/views/users/_online_users.html.slim
- if member.online == true
  <li id="user_#{member.id}" class="user-login">
    = member.name + "：オンライン(DB)"
  </li>
- elsif member.online == false
  <li id="user_#{member.id}" class="user-logout">
    = member.name + "：オフライン(DB)" + " 最終オンライン時間：" + member.online_at.strftime('%Y/%m/%d %H:%M:%S')
  </li>

app/views/users/edit.html.slim
h1
  | Editing User
= render 'form', user: @user
= link_to 'Show', @user
|  | 
= link_to 'Back', users_path

app/views/users/index.html.slim
h1
  | All_Users
table
  thead
    tr
      th[colspan="3"]
  tbody
    - @users.each do |user|
      tr
        td
          = user.name
        / TODO:以下は管理者のみ利用可能にする
        / td
        /   = link_to 'Show', user
        / td
        /   = link_to 'Edit', edit_user_path(user)
        / td
        /   = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
h1
  | Online_Users
p ユーザーのオンライン状況がリアルタイムで見られるよ！
table
  thead
    tr
      th[colspan="3"]
  tbody
    span#users-list.logbox
      = render partial: 'online_users', collection: @online_users, as: :member

app/views/users/new.html.slim
h1
  | New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.slim
= link_to 'Edit', edit_user_path(@user)
|  | 
= link_to 'Back', users_path